service: rpi-aws-iot-prototype
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  region: us-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: "arn:aws:s3:::rpi-atmospheric-data/*"

constructs:
  sensor-events:
    type: queue
    worker:
      handler: handler.data_appender
      environment:
        S3_BUCKET: rpi-atmospheric-data

functions:
  eventReceiver:
    handler: handler.event_receiver
    memorySize: 256
    environment:
      QUEUE_URL: ${construct:sensor-events.queueUrl}
  fetchData:
    handler: handler.fetch_data
    memorySize: 256
    environment:
      S3_BUCKET: rpi-atmospheric-data
    events:
      - http:
          path: /fetch
          method: GET

resources:
  Resources:
    AllEventsRule:
      Type: "AWS::IoT::TopicRule"
      Properties:
        RuleName: all_events_rule
        TopicRulePayload:
          Sql: "SELECT * FROM 'rpi/sensor/events'"
          Actions:
            - Lambda:
                FunctionArn:
                  Fn::GetAtt:
                    # Note that the function name "EventReceiverLambdaFunction" corresponds to the "eventReceiver"
                    # function declared under the "functions" section. This is just the way that Serverless
                    # Framework, by convention, names functions using the function key under "functions"
                    - EventReceiverLambdaFunction
                    - Arn
    RPiB3Home:
      Type: "AWS::IoT::Thing"
      Properties:
        ThingName: RPi3BHome

plugins:
  - serverless-lift
  - serverless-python-requirements

package:
  patterns:
    - "!node_modules/**"
